# Generated by Django 3.2 on 2025-06-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('rol', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conductor',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.usuario')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
